server:
  port: 8300
  servlet:
    context-path: /v1/
  

spring:
  application:
    name: transparencia
  datasource:
    url: jdbc:h2:mem:transparencia
    sqlScriptEncoding: UTF-8 
  h2:
    console:
      enabled: true

security:
  oauth2:
    resource:
      jwt:
        key-value: secret-sgq
            
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instanceId: ${spring.application.name}:${random.value} 
    preferIpAddress: true