server:
  port: 8300
  servlet:
    context-path: /v1/
  
spring:
  application:
    name: transparencia
  datasource:
    url: jdbc:h2:mem:transparencia
    sqlScriptEncoding: UTF-8 
  h2:
    console:
      enabled: true
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instanceId: ${spring.application.name}:${random.value} 
    preferIpAddress: true

sgq:
  authorizationServer:
    url: ${AUTH_URL:http://localhost:8086/oauth}/token
    credential: c2dxOnFncw==
    username: ${AUTH_USER:interno}
    password: ${AUTH_PASS:i123}