version: "3.7"

services: 
    nginx:
        image: nginx:1.17-alpine
        container_name: sgq-front-proxy
        network_mode: "host"
        ports: 
            - "80:80"
        environment: 
          - NGINX_PORT=80
        volumes: 
          - ./sgq_site.conf:/etc/nginx/conf.d/default.conf
          
