server:
  port: 8086
  
spring:
  application:
    name: authorization-server
  datasource:
    url: jdbc:h2:mem:authorization_server
    sqlScriptEncoding: UTF-8
  h2:
    console:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instanceId: ${spring.application.name}:${random.value} 
    preferIpAddress: true

security:
  oauth2:
    client:
      client-id: sgq
      client-secret: "{noop}qgs"
      
sgq:
  security:
    jwt-secret: secret-sgq