server:
  port: 8100
  servlet:
    context-path: /v1/

spring:
  application:
    name: gestao-incidentes
  datasource:
    url: jdbc:h2:mem:gestao_incidente
    sqlScriptEncoding: UTF-8
  h2:
    console:
      enabled: true
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instanceId: ${spring.application.name}:${random.value} 
    preferIpAddress: true


sgq:
  integracao:
    gestao-normas:
      host: http://localhost:18080
      credencial: 123123123123123