server:
  port: 9000
  servlet:
    context-path: /v1

spring:
  application:
    name: gw-normas
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instanceId: ${spring.application.name}:${random.value} 
    preferIpAddress: true


sgq:
  integracao:
    gestao-normas:
      host: http://localhost:18080
      credencial: 123123123123123
