server:
  port: 9090
  servlet:
    context-path: /v1/

spring:
  application:
    name: gw-normas
  cache:
    ehcache:
      config: classpath:ehcache.xml
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8000/eureka/
  instance:
    instanceId: ${spring.application.name}:${random.value} 
    preferIpAddress: true

security:
  oauth2:
    resource:
      jwt:
        key-value: secret-sgq

sgq:
  integracao:
    gestao-normas:
      host: http://${MOCK_GESTAO_HOST:localhost}:18080
   