server:
  port: 8600
  servlet:
    context-path: /v1/

spring:
  application:
    name: relatorios
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instanceId: ${spring.application.name}:${random.value} 
    preferIpAddress: true
    
sgq:
  relatorios:
    diretorio: /tmp/relatorios